import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { BetsService } from '../../services/bets.service';
import { Subscription } from 'rxjs';
import { Settings } from '../../settings/settings';

@Component({
  selector: 'app-ball-selector',
  templateUrl: './ball-selector.component.html',
  styleUrls: ['./ball-selector.component.css']
})
export class BallSelectorComponent implements OnDestroy {

  dataUserSelection = Settings.DATAUSERSELECTION;
  resultadoSorteo: number;
  win: boolean = false;
  finishSorteo: boolean = false;
  selectItemUser: number = undefined;

  sorteoSubs: Subscription;

  constructor(private service: BetsService) {

    //
    // get the result of the draw generated by the service
    //
    this.sorteoSubs = this.service.getSorteo().subscribe(resp => {
      this.resultadoSorteo = resp;
      if(this.selectItemUser === this.resultadoSorteo ){
        this.win = true;
      }else{
        this.win = false;
      }
      this.finishSorteo = true;
    })

  }


  ngOnDestroy() {
    // unsubscribe to ensure no memory leaks
    this.sorteoSubs.unsubscribe();
  }

  // set number selected for user 'click ball'
  // Before selection clean
  // Save ball an variable for check results
  selectionUser(ball){
    this.selectItemUser = ball;
    this.clearSelection();
    this.service.setUserSelection(this.selectItemUser);
  }

  clearSelection(){
    this.win = false;
    this.finishSorteo = false;
    this.service.clear();
  }
}
